/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedArtesRouteImport } from './routes/_authenticated/artes'
import { Route as AuthenticatedConteudosRouteImport } from './routes/_authenticated/conteudos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLegendasRouteImport } from './routes/_authenticated/legendas'
import { Route as AuthenticatedPlanejamentoRouteImport } from './routes/_authenticated/planejamento'
import { Route as AuthenticatedVersiculosRouteImport } from './routes/_authenticated/versiculos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedArtesRoute = AuthenticatedArtesRouteImport.update({
  id: '/artes',
  path: '/artes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConteudosRoute = AuthenticatedConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLegendasRoute = AuthenticatedLegendasRouteImport.update({
  id: '/legendas',
  path: '/legendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanejamentoRoute =
  AuthenticatedPlanejamentoRouteImport.update({
    id: '/planejamento',
    path: '/planejamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVersiculosRoute = AuthenticatedVersiculosRouteImport.update({
  id: '/versiculos',
  path: '/versiculos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/artes': typeof AuthenticatedArtesRoute
  '/conteudos': typeof AuthenticatedConteudosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/legendas': typeof AuthenticatedLegendasRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/versiculos': typeof AuthenticatedVersiculosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/artes': typeof AuthenticatedArtesRoute
  '/conteudos': typeof AuthenticatedConteudosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/legendas': typeof AuthenticatedLegendasRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/versiculos': typeof AuthenticatedVersiculosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/artes': typeof AuthenticatedArtesRoute
  '/_authenticated/conteudos': typeof AuthenticatedConteudosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/legendas': typeof AuthenticatedLegendasRoute
  '/_authenticated/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/_authenticated/versiculos': typeof AuthenticatedVersiculosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/artes'
    | '/conteudos'
    | '/dashboard'
    | '/legendas'
    | '/planejamento'
    | '/versiculos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/artes'
    | '/conteudos'
    | '/dashboard'
    | '/legendas'
    | '/planejamento'
    | '/versiculos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/artes'
    | '/_authenticated/conteudos'
    | '/_authenticated/dashboard'
    | '/_authenticated/legendas'
    | '/_authenticated/planejamento'
    | '/_authenticated/versiculos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/artes': {
      id: '/_authenticated/artes'
      path: '/artes'
      fullPath: '/artes'
      preLoaderRoute: typeof AuthenticatedArtesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conteudos': {
      id: '/_authenticated/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof AuthenticatedConteudosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/legendas': {
      id: '/_authenticated/legendas'
      path: '/legendas'
      fullPath: '/legendas'
      preLoaderRoute: typeof AuthenticatedLegendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planejamento': {
      id: '/_authenticated/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AuthenticatedPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/versiculos': {
      id: '/_authenticated/versiculos'
      path: '/versiculos'
      fullPath: '/versiculos'
      preLoaderRoute: typeof AuthenticatedVersiculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArtesRoute: typeof AuthenticatedArtesRoute
  AuthenticatedConteudosRoute: typeof AuthenticatedConteudosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLegendasRoute: typeof AuthenticatedLegendasRoute
  AuthenticatedPlanejamentoRoute: typeof AuthenticatedPlanejamentoRoute
  AuthenticatedVersiculosRoute: typeof AuthenticatedVersiculosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArtesRoute: AuthenticatedArtesRoute,
  AuthenticatedConteudosRoute: AuthenticatedConteudosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLegendasRoute: AuthenticatedLegendasRoute,
  AuthenticatedPlanejamentoRoute: AuthenticatedPlanejamentoRoute,
  AuthenticatedVersiculosRoute: AuthenticatedVersiculosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
